Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval














































































































































































































































































































































































































































































































































































































































































































































































































100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 802/802 [26:53<00:00,  2.01s/batch, epoch=0, loss=3.05, mse=110, psnr=29.6]
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 1614.01s
I1121 14:40:16.053651 140616146092416 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 1614.01s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 96, in test_train_eval
    ckpt_p = model.write_ckpt(args.write_ckpt_dir, step=epoch)
AttributeError: 'Model' object has no attribute 'write_ckpt'
----------------------------------------------------------------------
Ran 2 tests in 1614.210s
FAILED (errors=1, skipped=1)