Running tests under Python 3.10.9: /home/lab-com/anaconda3/bin/python3
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 0.0s
I0426 19:31:48.748293 140000914727552 test_util.py:2472] time(__main__.ModelsTest.test_train_eval): 0.0s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/backup/FILM/vfi/src/train.py", line 70, in test_train_eval
    config=Options()
NameError: name 'Options' is not defined
----------------------------------------------------------------------
Ran 2 tests in 0.001s
FAILED (errors=1, skipped=1)