Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 0.0s
I1121 19:11:01.633771 140006332100992 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 0.0s
[  FAILED  ] ModelsTest.test_train_eval
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/my_film/src/models_test.py", line 70, in test_train_eval
    model= Model()
  File "/home/jmw/ing/myfi/my_film/src/model.py", line 45, in __init__
    self.flow_num_stage = len(kargs['hidden_dims']) #2
NameError: name 'kargs' is not defined
----------------------------------------------------------------------
Ran 2 tests in 0.001s
FAILED (errors=1, skipped=1)