Running tests under Python 3.10.9: /home/lab-com/anaconda3/bin/python3
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval





























































































































































































































































































































































 35%|██████████████████████████████████████████████████████▉                                                                                                      | 561/1604 [12:12<22:42,  1.31s/batch, epoch=0, loss=0.0355, mse=293, psnr=24.4]
Traceback (most recent call last):
  File "/home/lab-com/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lab-com/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jmw/backup/FILM/vfi/src/train.py", line 103, in <module>
    tf.test.main()
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/platform/test.py", line 56, in main
    return _googletest.main(argv)
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/platform/googletest.py", line 62, in main
    benchmark.benchmarks_main(true_main=main_wrapper, argv=argv)
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/platform/benchmark.py", line 489, in benchmarks_main
    true_main()
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/platform/googletest.py", line 60, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/platform/googletest.py", line 51, in g_main
    absltest_main(argv=argv)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/testing/absltest.py", line 2070, in main
    _run_in_app(run_tests, args, kwargs)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/testing/absltest.py", line 2165, in _run_in_app
    function(argv, args, kwargs)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/testing/absltest.py", line 2628, in run_tests
    result, fail_when_no_tests_ran = _run_and_get_tests_result(
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/testing/absltest.py", line 2592, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/jmw/.local/lib/python3.10/site-packages/absl/testing/_pretty_print_reporter.py", line 82, in run
    return super(TextTestRunner, self).run(test)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/home/lab-com/anaconda3/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/jmw/backup/FILM/vfi/src/train.py", line 88, in test_train_eval
    img0 = tf.cast(img0/255.0, dtype=tf.float32)
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 140, in error_handler
    if not is_traceback_filtering_enabled():
  File "/home/jmw/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 32, in is_traceback_filtering_enabled
    @tf_export('debugging.is_traceback_filtering_enabled')
KeyboardInterrupt